

- name: Get the wheel name
  set_fact:
    wheel_name: "{{ python2wheels.key }}"
  become: yes
  changed_when: false

- name: Get the wheel file
  set_fact:
    wheel_file_name: "{{python2wheels.value }}"
  become: yes
  changed_when: false

- debug:
    msg: "Package: {{wheel_name}}:{{wheel_file_name}}"

- name: Install python2 package
  shell: /ngs/app/amlbin/python2/bin/pip2 install --quiet --no-index --no-deps --find-links=/ngs/app/{{ PROJECT_USERNAME }}/{{ UNIX_ID }}/python2/wheels {{wheel_name}}
  register: wheel_install_msg
  ignore_errors: yes

- debug:
    msg: "{{ wheel_install_msg }}"
