


- include: download_packages.yml
  with_dict: "{{bootstrap_definition_content.rpms_oel6}}"
  loop_control:
    loop_var: rpms
  when: (bootstrap_definition_content['ansibleprops']['collect_artifacts_locally'] == True and ansible_distribution_major_version == '6')


- include: download_packages.yml
  with_dict: "{{bootstrap_definition_content.rpms_oel7}}"
  loop_control:
    loop_var: rpms
  when: (bootstrap_definition_content['ansibleprops']['collect_artifacts_locally'] == True and ansible_distribution_major_version == '7')
