

- hosts: all
  serial: 5
  gather_facts: yes
  vars:
      project_env: "{{ lookup('env','ANSIBLE_PROJECT_ENV') }}"
      bootstrap_definition_file: "{{ SALT_PROJECT_GIT_PATH }}/environs/{{ ANSIBLE_PROJECT_ENV }}/saltconf/bootstrap.yaml"
  pre_tasks:
    - debug: msg="=======  Restarting salt minions!  ======"
  roles:
    - { role: prep_read_bootstrap }
    - { role: amlbin_stop_salt_minion }
    - { role: amlbin_start_salt_minion }
