# Help start
#  This ansible playbook create new set of gpg keys
#  for salt gpgring
#
# Help end


- hosts: saltmaster
  serial: 1
  gather_facts: yes
  vars:
      project_env: "{{ lookup('env','ANSIBLE_PROJECT_ENV') }}"
  pre_tasks:
    - debug: msg="=======  Setup saltmaster gpg keys  ======"
  roles:
    - {role: saltmaster_update_saltgpg}
